struct Vertex {
  vec3 pos;
  vec3 norm;
  vec3 color;
};

layout(std140, binding = 0) uniform ParameterUBO {
  mat4 model;
  mat4 view;
  mat4 proj;
  float deltaTime;
}

layout(std140, binding = 1) readonly buffer VertexSSBOIn {
  Vertex verticesIn[ ];
};

layout(std140, binding = 2) buffer VertexSSBOOut {
  Vertex verticesOut[ ];

};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
